### PR TITLE
Updated the README_MG.md

### LINKED ISSUE #17: Add Malagasy Translation [ README.md ]
Add 🇲🇬  translation to the README.md

### PR DESCRIPTION
**Pull request by Subhangini**
Added the documentation in Malagasy language
resolves #17

### CODE REVIEW

**Comment by Subhangini** [comment]
@PyladiesTNR  Please review this PR

**Comment by PyladiesTNR** [comment]
There are typos and words that don't make sense but we will fix that.

**Comment by Subhangini** [comment]
Ok sorry for that as i told i don't know thid language so . Thank you for
accepting my contribution.

**Comment by Subhangini** [comment]
@Mahalinoro @PyladiesTNR Please add `hacktoberfest-accepted` label.

**Comment by Subhangini** [comment]
Thanks :) @Mahalinoro

**Pull request merged**
